# Dataset
dataset: 'prw'
dataset_dir: '/home/ubuntu/datasets/PRW'
train_set: 'trainval'
test_set: 'test'
retrieval_name_list: ('test',)
workers: 8
# OIM
oim_type: "LOIM"
oim_cq_size: 500
### OIM LUT update momentum
oim_momentum: 0.5
### Inverse temperature parameter
oim_scalar: 30.0
emb_norm_type: 'protonorm'
decouple_mode: False
# Model
# model: 'resnet'
# backbone_arch: 'resnet50'
model: 'convnext'
backbone_arch: 'convnext_fpn'
user_arm_module: False
pretrained: True


# GFN
use_gfn: False
# gfn_mode: 'combined'
# gfn_query_mode: 'batch'
# gfn_scene_pool_size: 56

# Optimization
epochs: 50
batch_size: 8
# use_amp: False
lr_steps: (20, 35)

# Augmentation
aug_mode: 'rrc2'
aug_crop_res: 640


# Logging
trial_name: 'prw_final'
eval_interval: 5
ckpt_interval: 10
log_dir: './logging'

# box_head_mode: 'nae'
share_head: False
debug: ~ 