# Dataset
dataset: 'prw'
dataset_dir: '/home/ubuntu/datasets/PRW'
train_set: 'trainval'
test_set: 'test'
retrieval_name_list: ('test', 'cross_cam_id', 'same_cam_id')

# OIM
oim_cq_size: 500

# Model
model: 'convnext'
backbone_arch: 'convnext_base'

# # GFN
# gfn_mode: 'combined'
# gfn_query_mode: 'batch'
# gfn_scene_pool_size: 56

# # Optimization
# epochs: 1
# batch_size: 8

# # Augmentation
# aug_mode: 'rrc2'
# aug_crop_res: 640

# # Run mode
# test_only: True

# # Logging
# trial_name: 'prw_final'
# eval_interval: 30
# ckpt_interval: 30
# log_dir: './logging'
# ckpt_path: '/home/ubuntu/GFN/logging/prw_final/WrappedDistributedTorchTrainable_52cb9_00000_0_2022-11-03_18-00-19/checkpoint_000030/checkpoint.pkl'

# GFN
use_gfn: False
gfn_mode: 'combined'
gfn_query_mode: 'batch'
gfn_scene_pool_size: 56

# Optimization
epochs: 1
batch_size: 8
test_only: True

# Augmentation
aug_mode: 'rrc2'
aug_crop_res: 640

# Logging
trial_name: 'prw_final'
eval_interval: 30
ckpt_interval: 30
log_dir: './logging'
ckpt_path: '/home/ubuntu/GFN/logging/prw_final/WrappedDistributedTorchTrainable_06309_00000_0_2023-03-06_10-38-49/checkpoint_000030/checkpoint.pkl'